sudo: required
dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
  - "node"
before_install:
  - npm install -g npm@5.6.0
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - ng lint
  - ng test && ng e2e
